import bodyParser from "body-parser";
import express from "express";
import route from "./routes/router.js";
import cors from "cors";
import connection from "./database/db.js";
import path from "path";
import { fileURLToPath } from "url";
import { dirname } from "path";
const app = express();
app.use(express.json());
app.use(bodyParser.json({ extended: true }));
app.use(bodyParser.urlencoded({ extended: true }));
app.use(cors());
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
app.use("/files", express.static(path.join(__dirname, "/images")));
connection();
app.use("/", route);
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`server started at ${PORT}`);
});
